# Generated by Django 3.1.7 on 2021-05-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('faculty_number', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=50)),
            ],
        ),
    ]
